### ISSUE TITLE
Does it contain profanity?

### ISSUE THREAD

**Issue by ukazap** [schmich/spicy-proton#18]
Can we ensure that the generated string is SFW?

**Comment by schmich** [comment]
I can't make any hard guarantees since I didn't build the word lists myself (they come from [NLTK](http://www.nltk.org/)), but there have been [many pull requests](https://github.com/schmich/spicy-proton/pulls?q=is%3Apr+is%3Aclosed) to remove NSFW words and phrases, erring on the side of caution.

As a point of confidence, this library has been in use by [vmpooler from Puppet](https://github.com/puppetlabs/vmpooler) for some time. They've contributed the most to cleaning up the word lists.

If you want to be extra sure, you can find a list of NSFW words and compare it against the plaintext word lists that this library uses: https://github.com/schmich/spicy-proton/tree/master/corpus
